/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as MilestonesRouteImport } from './routes/milestones'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SoundsRouteImport } from './routes/sounds'
import { Route as TourRouteImport } from './routes/tour'
import { Route as CheckoutReturnRouteImport } from './routes/checkout/return'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestonesRoute = MilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundsRoute = SoundsRouteImport.update({
  id: '/sounds',
  path: '/sounds',
  getParentRoute: () => rootRouteImport,
} as any)
const TourRoute = TourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/family': typeof FamilyRoute
  '/growth': typeof GrowthRoute
  '/milestones': typeof MilestonesRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sounds': typeof SoundsRoute
  '/tour': typeof TourRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/family': typeof FamilyRoute
  '/growth': typeof GrowthRoute
  '/milestones': typeof MilestonesRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sounds': typeof SoundsRoute
  '/tour': typeof TourRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/family': typeof FamilyRoute
  '/growth': typeof GrowthRoute
  '/milestones': typeof MilestonesRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sounds': typeof SoundsRoute
  '/tour': typeof TourRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/auth'
    | '/family'
    | '/growth'
    | '/milestones'
    | '/onboarding'
    | '/reset-password'
    | '/sounds'
    | '/tour'
    | '/checkout/return'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/auth'
    | '/family'
    | '/growth'
    | '/milestones'
    | '/onboarding'
    | '/reset-password'
    | '/sounds'
    | '/tour'
    | '/checkout/return'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/auth'
    | '/family'
    | '/growth'
    | '/milestones'
    | '/onboarding'
    | '/reset-password'
    | '/sounds'
    | '/tour'
    | '/checkout/return'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  AuthRoute: typeof AuthRoute
  FamilyRoute: typeof FamilyRoute
  GrowthRoute: typeof GrowthRoute
  MilestonesRoute: typeof MilestonesRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SoundsRoute: typeof SoundsRoute
  TourRoute: typeof TourRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestones': {
      id: '/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof MilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sounds': {
      id: '/sounds'
      path: '/sounds'
      fullPath: '/sounds'
      preLoaderRoute: typeof SoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour': {
      id: '/tour'
      path: '/tour'
      fullPath: '/tour'
      preLoaderRoute: typeof TourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  AuthRoute: AuthRoute,
  FamilyRoute: FamilyRoute,
  GrowthRoute: GrowthRoute,
  MilestonesRoute: MilestonesRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SoundsRoute: SoundsRoute,
  TourRoute: TourRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
